version: '3.1'
services:
#  frontend:
#    build: .
#    container_name: angular
#    ports:
#      - "4200:80"
#    depends_on:
#      - api
#      - PostgreSQL
#    network_mode: bridge


  api:
    build: .
    container_name: springapp
    ports:
      - "8080:8081"
    depends_on:
     - PostgreSQL
    network_mode: bridge
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/clube
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: 'postgres:13.1-alpine'
    container_name: db
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clube
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5