spring:
  profiles:
    active: local
  application:
    name:

  main:
    allow-circular-references: true
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-201-95-176.compute-1.amazonaws.com:5432/d9jed17qo1ks37
    username: xffnpwvmjjikip
    password: b32c58e618dc4ceb9d6e27515e3620b3bc1e6a63591fdb9ebe4b5e3f21141fb9
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      springframework:
        security: DEBUG
        hibernate: DEBUG

server:
  port: $PORT #set your port
jwt:
  secret: secret